const { cpSync, mkdirSync } = require('fs');
const path = require('path');
const { FusesPlugin } = require('@electron-forge/plugin-fuses');
const { FuseV1Options, FuseVersion } = require('@electron/fuses');

module.exports = {
  packagerConfig: {
    asar: {
      // node-llama-cpp and sherpa-onnx-node are native ESM packages whose
      // binaries cannot execute from inside an asar archive. Unpacking them
      // places them in app.asar.unpacked/ where Node.js ESM resolution works.
      unpack: '**/node_modules/{node-llama-cpp,@node-llama-cpp,sherpa-onnx-node}/**',
    },
    // The Vite plugin bundles all JS dependencies and excludes node_modules from
    // the package. Native ESM modules (node-llama-cpp, sherpa-onnx-node) cannot
    // be bundled, so we copy them manually into the staging directory here.
    // asarUnpack above then extracts them to app.asar.unpacked/ at package time.
    afterCopy: [
      (buildPath, _electronVersion, _platform, _arch, callback) => {
        const srcModules = path.join(__dirname, 'node_modules');
        const destModules = path.join(buildPath, 'node_modules');
        // Native ESM packages + all their hoisted transitive deps.
        // The Vite plugin excludes node_modules from the bundle, so we must
        // manually inject everything node-llama-cpp and sherpa-onnx-node need
        // at runtime. Generated by tracing the full dep tree recursively.
        const packages = [
          // Native packages
          'node-llama-cpp',
          path.join('@node-llama-cpp', 'win-x64'),
          path.join('@node-llama-cpp', 'win-x64-cuda'),
          path.join('@node-llama-cpp', 'win-x64-vulkan'),
          'sherpa-onnx-node',
          'sherpa-onnx-win-x64',
          // node-llama-cpp direct deps (hoisted, not nested inside it)
          path.join('@huggingface', 'jinja'),
          path.join('@kwsites', 'file-exists'),
          path.join('@kwsites', 'promise-deferred'),
          path.join('@simple-git', 'args-pathspec'),
          path.join('@simple-git', 'argv-parser'),
          path.join('@tinyhttp', 'content-disposition'),
          'ansi-escapes',
          'ansi-regex',
          'ansi-styles',
          'async-retry',
          'bytes',
          'chalk',
          'chmodrp',
          'chownr',
          'ci-info',
          'cli-spinners',
          'cliui',
          'cmake-js',
          'color-convert',
          'color-name',
          'commander',
          'cross-spawn',
          'debug',
          'deep-extend',
          'eastasianwidth',
          'emoji-regex',
          'env-var',
          'escalade',
          'escape-string-regexp',
          'eventemitter3',
          'filename-reserved-regex',
          'filenamify',
          'fs-extra',
          'fs-minipass',
          'get-caller-file',
          'get-east-asian-width',
          'graceful-fs',
          'has-flag',
          'ignore',
          'ini',
          'ipull',
          'is-fullwidth-code-point',
          'is-unicode-supported',
          'isexe',
          'jsonfile',
          'lifecycle-utils',
          'lowdb',
          'mimic-function',
          'minimist',
          'minipass',
          'minizlib',
          'ms',
          'node-addon-api',
          'node-api-headers',
          'parse-ms',
          'path-key',
          'pretty-bytes',
          'pretty-ms',
          'proper-lockfile',
          'rc',
          'require-directory',
          'retry',
          'semver',
          'shebang-command',
          'shebang-regex',
          'signal-exit',
          'simple-git',
          'sleep-promise',
          'slice-ansi',
          'stdin-discarder',
          'stdout-update',
          'steno',
          'string-width',
          'strip-ansi',
          'strip-json-comments',
          'supports-color',
          'tar',
          'universalify',
          'url-join',
          'validate-npm-package-name',
          'which',
          'wrap-ansi',
          'y18n',
          'yallist',
          'yargs',
          'yargs-parser',
          'yoctocolors',
          // Additional transitive deps of ipull / node-llama-cpp / sherpa-onnx-node
          // missed by the original trace. ipull statically imports lodash.debounce
          // in its transfer-cli, which crashed warm-builtin on fresh installs with
          // ERR_MODULE_NOT_FOUND. These complete the dependency closure.
          'base64-js',
          'bl',
          'buffer',
          'cli-cursor',
          'clone',
          'defaults',
          'ieee754',
          'inherits',
          'is-interactive',
          'lodash.debounce',
          'log-symbols',
          'mimic-fn',
          'mkdirp',
          'nanoid',
          'onetime',
          'ora',
          'readable-stream',
          'restore-cursor',
          'safe-buffer',
          'string_decoder',
          'strip-outer',
          'trim-repeated',
          'type-fest',
          'util-deprecate',
          'wcwidth',
        ];
        try {
          for (const pkg of packages) {
            const src = path.join(srcModules, pkg);
            const dest = path.join(destModules, pkg);
            if (!require('fs').existsSync(src)) continue;
            mkdirSync(path.dirname(dest), { recursive: true });
            cpSync(src, dest, { recursive: true });
          }
          callback();
        } catch (err) {
          callback(err);
        }
      },
    ],
    executableName: 'VoiceRefine',
    icon: 'resources/icons/icon',
    appCopyright: `Copyright (c) ${new Date().getFullYear()} Akshita Garg`,
    win32metadata: {
      CompanyName: 'VoiceRefine',
      FileDescription: 'VoiceRefine',
      OriginalFilename: 'VoiceRefine.exe',
      ProductName: 'VoiceRefine',
      InternalName: 'VoiceRefine',
    },
    // Bundle only the current user-facing local models and Windows sidecar binary.
    // extraResource items land in process.resourcesPath at runtime.
    extraResource: [
      'resources/models/gemma-3-1b-it-Q4_K_M.gguf',
      'resources/models/parakeet-tdt-0.6b-v3-GGUF',
      'resources/models/sherpa-onnx-whisper-tiny.en',
      'resources/bin/crispasr-windows-x86_64-cpu',
    ],
  },
  rebuildConfig: {},
  makers: [
    {
      name: '@electron-forge/maker-zip',
      platforms: ['darwin', 'win32'],
    },
    {
      name: '@electron-forge/maker-deb',
      config: {},
    },
    {
      name: '@electron-forge/maker-rpm',
      config: {},
    },
  ],
  plugins: [
    {
      name: '@electron-forge/plugin-vite',
      config: {
        // `build` can specify multiple entry builds, which can be Main process, Preload scripts, Worker process, etc.
        // If you are familiar with Vite configuration, it will look really familiar.
        build: [
          {
            // `entry` is just an alias for `build.lib.entry` in the corresponding file of `config`.
            entry: 'src/main.js',
            config: 'vite.main.config.mjs',
            target: 'main',
          },
          {
            entry: 'src/preload.js',
            config: 'vite.preload.config.mjs',
            target: 'preload',
          },
        ],
        renderer: [
          {
            name: 'main_window',
            config: 'vite.renderer.config.mjs',
          },
          {
            name: 'overlay_window',
            config: 'vite.overlay.config.mjs',
          },
        ],
      },
    },
    // Fuses are used to enable/disable various Electron functionality
    // at package time, before code signing the application
    new FusesPlugin({
      version: FuseVersion.V1,
      [FuseV1Options.RunAsNode]: false,
      [FuseV1Options.EnableCookieEncryption]: true,
      [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
      [FuseV1Options.EnableNodeCliInspectArguments]: false,
      [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
      [FuseV1Options.OnlyLoadAppFromAsar]: true,
    }),
  ],
};
